#!/usr/bin/env sh

# Récupérer fichier HTML 
HTML_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.html$')

if [ -z "$HTML_FILES" ]; then
  echo "Aucun fichier HTML"
  exit 0
fi

echo "$HTML_FILES"
echo ""

# Lancer HTMLHint
npx htmlhint $HTML_FILES
 
if [ $? -ne 0 ]; then
  echo "Commit bloqué !"
  echo "Corrigez les erreurs HTML avant de commiter."
  exit 1
fi

echo "HTML validé ! Commit autorisé."
exit 0
